# 1 -  Análisis de sentimientos

**Objetivo**

Entrenar un modelo de clasificación que permita identificar si una reseña de película es positiva o negativa.

**Los datos**

Nuestro proyecto consistirá en entrenar un modelo de análisis de sentimiento para identificar reseñas positivas y negativas de películas. Utilizaremos una base de datos de 50,000 reseñas de películas en IMDB (25,000 positivas y 25,000 negativas).

## Importación de librerías y carga de datos

In [2]:
import numpy as np 
import pandas as pd 
import matplotlib.pyplot as plt
import seaborn as sns
sns.set_style('darkgrid')

In [27]:
df = pd.read_csv("./data/IMDB Dataset.csv")

## Exploración de datos

Comenzamos inspeccionando los datos:

In [28]:
df.head()

                                              review sentiment
0  One of the other reviewers has mentioned that ...  positive
1  A wonderful little production. <br /><br />The...  positive
2  I thought this was a wonderful way to spend ti...  positive
3  Basically there's a family where a little boy ...  negative
4  Petter Mattei's "Love in the Time of Money" is...  positive

In [30]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 50000 entries, 0 to 49999
Data columns (total 2 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   review     50000 non-null  str
 1   sentiment  50000 non-null  str
dtypes: str(2)
memory usage: 781.4 KB

Nuestro conjunto de datos tiene dos columnas:

Review:  Reseña que escribió alguna persona acerca de una película (no sabemos a qué película fue, pero no es relevante para este análisis).

Sentiment: Si la reseña fue positiva o negativa (negative o positive)

Finalmente, veamos cuántas reseñas positivas y cuántas negativas tenemos:

In [31]:
df.sentiment.value_counts()

sentiment
positive    25000
negative    25000
Name: count, dtype: int64

Estamos por comenzar a hacer análisis de sentimiento usando Python. Nuestro modelo será capaz de determinar si una reseña es positiva o negativa. Por ejemplo, después de entrenar nuestro modelo, si le pedimos que analice el texto “I really loved this movie,” nuestro modelo debería indicarnos que se trata de una reseña positiva.

Esto podría dar la impresión de que la computadora está comprendiendo el texto o el lenguaje de la misma manera que lo haría un ser humano. Sin embargo, lo que haremos es algo que, aunque suene sorprendente, es fundamental en el procesamiento de lenguaje natural. Vamos a convertir los enunciados en una representación numérica. A esto se le conoce como vectorización del texto.

Mediante técnicas como TF-IDF, podemos transformar las palabras y frases en vectores, que son simplemente listas de números que representan la importancia de cada término en el contexto del texto. Estos vectores son los que el modelo utiliza para "comprender" el contenido y realizar predicciones sobre el sentimiento de la reseña.

Este proceso no implica comprensión del lenguaje en el sentido humano, sino una interpretación matemática que permite al modelo hacer inferencias basadas en patrones observados durante su entrenamiento.

## Preparación de datos

Este proceso de entrenamiento será mucho más pesado que otros que hemos visto anteriormente. Por lo tanto, para fines demostrativos, reduciremos el tamaño de nuestros datos. Tomaremos 5,000 reseñas positivas y 5,000 negativas

In [35]:
df_pos = df[df['sentiment']=='positive'][:5000]
df_neg = df[df['sentiment']=='negative'][:5000]

df_reviews = pd.concat([df_pos, df_neg ])

df_reviews.info()
df_reviews.sentiment.value_counts()

<class 'pandas.DataFrame'>
Index: 10000 entries, 0 to 10048
Data columns (total 2 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   review     10000 non-null  str
 1   sentiment  10000 non-null  str
dtypes: str(2)
memory usage: 234.4 KB

sentiment
positive    5000
negative    5000
Name: count, dtype: int64

## División de datos

In [36]:
from sklearn.model_selection import train_test_split

train,test = train_test_split(df_reviews,test_size =0.33,random_state=42)

train_x, train_y = train['review'], train['sentiment']
test_x, test_y = test['review'], test['sentiment']


# Imprimir shapes
print("train_x:", train_x.shape)
print("train_y:", train_y.shape)
print("test_x:", test_x.shape)
print("test_y:", test_y.shape)

train_x: (6700,)
train_y: (6700,)
test_x: (3300,)
test_y: (3300,)

Si inspeccionamos train_y, vemos:

In [37]:
train_y.value_counts()

sentiment
negative    3378
positive    3322
Name: count, dtype: int64

## De texto a números

Ahora procederemos a transformar nuestros valores de texto a valores numéricos. Para esto, usaremos Scikit Learn. Específicamente, utilizaremos la clase TfidfVectorizer para transformar texto en una representación numérica utilizando el esquema TF-IDF (Term Frequency-Inverse Document Frequency).

Nuestro código es el siguiente:

In [11]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [12]:
tfidf = TfidfVectorizer(stop_words='english')
train_x_vector = tfidf.fit_transform(train_x)
test_x_vector = tfidf.transform(test_x)

TfidfVectorizer es una clase utilizada para convertir una colección de documentos de texto en una matriz de características.

TF-IDF es una técnica que combina dos estadísticas:

Term Frequency (TF): Frecuencia de un término en un documento, que mide la importancia del término en el documento en cuestión.

Inverse Document Frequency (IDF): Mide la importancia del término en lque a colección de documentos. Penaliza los términos que son muy comunes en todos los documentos.

Llama la atención el argumento “stop_words”. Este arugmento se utilizara para indicar que se deben eliminar las palabras comunes en inglés (como "the", "and", "is", etc.) que no aportan información relevante para el análisis.

Inspeccionemos un poco nuestros objetos antes y después de transformar:

In [13]:
train_x.shape

(6700,)

Nada que nos sorprenda aquí. En train_x tenemos 6,700 reseñas en formato de texto. Ahora, ya tenemos una nueva variable train_x_vector, el cual resultó de ejectutar fit_transform sobre train_x.

In [14]:
train_x_vector.shape

(6700, 44107)

Resulta que ahora tenemos una matriz gigantesca. Esta matriz tiene 6,700 filas y 44,107 columnas. 

Inspeccionemos esto más de cerca:

In [15]:
type(train_x_vector)

scipy.sparse._csr.csr_matrix

El tipo de dato scipy.sparse._csr.csr_matrix es una representación eficiente de una matriz dispersa en formato CSR (Compressed Sparse Row), que se utiliza para almacenar y manipular matrices grandes y dispersas.

Una matriz dispersa es una matriz en la que la mayoría de los elementos son cero. Almacenar todos estos ceros de forma explícita sería ineficiente tanto en términos de espacio como de tiempo. Por eso, en lugar de almacenar la matriz completa, se utiliza una representación que solo guarda los elementos no nulos y su posición, lo que reduce significativamente el uso de memoria y mejora la eficiencia de las operaciones.

Pandas tiene una forma de trabajar con matrices dispersas de tipo csr_matrix:

In [40]:
pd.DataFrame.sparse.from_spmatrix(train_x_vector,
                                  index=train_x.index,
                                  columns=tfidf.get_feature_names_out())

,00,000,007,00am,00s,01,01pm,02,04,05,...,émigré,émigrés,était,étc,être,ísnt,île,önsjön,über,überwoman
6746,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
54,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8499,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7869,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3725,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1501,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
358,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
761,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1685,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4497,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [38]:
primera_resenia = pd.DataFrame.sparse.from_spmatrix(train_x_vector,
                                  index=train_x.index,
                                  columns=tfidf.get_feature_names_out()).iloc[0]

In [18]:
train_x.iloc[0]

"I happened to rent this movie with my sister in hopes of watching a great entertaining movie, that was humorous, however my expectations were let down. This movie was beyond disgusting and revolting for a PG-13 movie, this should have been rated R for the many mature references that went on in this movie. I wouldn't recommend allowing a 13 year old teen see this.<br /><br />Even if no one under the age of 17 is watching this movie, beware of a truly stupid movie, there's no humor in the movie, just a bunch of disgusting sexual references including a small touch of pedophilia, something that shouldn't even be joked about. <br /><br />I would like to know what happened to PG-13 movies, that were actually safe for actual a 13 year old? This is beyond a deplorable movie and should be re-rated."

In [19]:
primera_resenia[primera_resenia != 0]

00           NaN
000          NaN
007          NaN
00am         NaN
00s          NaN
            ...
ísnt         NaN
île          NaN
önsjön       NaN
über         NaN
überwoman    NaN
Name: 6746, Length: 44107, dtype: Sparse[float64, nan]

In [20]:
train_x.iloc[0]

"I happened to rent this movie with my sister in hopes of watching a great entertaining movie, that was humorous, however my expectations were let down. This movie was beyond disgusting and revolting for a PG-13 movie, this should have been rated R for the many mature references that went on in this movie. I wouldn't recommend allowing a 13 year old teen see this.<br /><br />Even if no one under the age of 17 is watching this movie, beware of a truly stupid movie, there's no humor in the movie, just a bunch of disgusting sexual references including a small touch of pedophilia, something that shouldn't even be joked about. <br /><br />I would like to know what happened to PG-13 movies, that were actually safe for actual a 13 year old? This is beyond a deplorable movie and should be re-rated."

## Entranamiento

Usaremos un modelo llamado Máquinas de Soporte Vectorial o Máquinas de Vectores de Soporte.

In [21]:
from sklearn.svm import SVC
svc = SVC(kernel='linear')
svc.fit(train_x_vector, train_y)

SVC(kernel='linear')

In [22]:
print(svc.predict(tfidf.transform(['A good movie'])))
print(svc.predict(tfidf.transform(['An excellent movie'])))
print(svc.predict(tfidf.transform(['I did not like this movie at all I gave this movie away'])))

['positive']
['positive']
['negative']

## Evaluación

### Precisión

In [23]:
print(svc.score(test_x_vector, test_y))

0.8706060606060606

### F1 Score

In [24]:
from sklearn.metrics import f1_score

f1_score(test_y,svc.predict(test_x_vector),
          labels = ['positive','negative'],average=None)

array([0.87400413, 0.86701962])

### Reporte de clasificación

In [25]:
from sklearn.metrics import classification_report

print(classification_report(test_y,
                            svc.predict(test_x_vector),
                            labels = ['positive','negative']))

              precision    recall  f1-score   support

    positive       0.87      0.88      0.87      1678
    negative       0.88      0.86      0.87      1622

    accuracy                           0.87      3300
   macro avg       0.87      0.87      0.87      3300
weighted avg       0.87      0.87      0.87      3300

### Matriz de confusión

In [26]:
from sklearn.metrics import confusion_matrix

conf_mat = confusion_matrix(test_y,
                           svc.predict(test_x_vector),
                           labels = ['positive', 'negative'])
conf_mat

array([[1481,  197],
       [ 230, 1392]])

## Modelo: LogisticRegression

In [42]:
from sklearn.linear_model import LogisticRegression

log_reg = LogisticRegression(max_iter=1000)
log_reg.fit(train_x_vector, train_y)

LogisticRegression(max_iter=1000)

In [43]:
print(log_reg.predict(tfidf.transform(['A good movie'])))
print(log_reg.predict(tfidf.transform(['An excellent movie'])))
print(log_reg.predict(tfidf.transform(['I did not like this movie at all I gave this movie away'])))

['positive']
['positive']
['negative']

In [46]:
from sklearn.metrics import f1_score, classification_report, confusion_matrix

# Accuracy (score)
print("Accuracy:", log_reg.score(test_x_vector, test_y))

# Precision y F1
y_pred = log_reg.predict(test_x_vector)
print("F1-score:", f1_score(test_y, y_pred, labels = ['positive','negative'],average=None))


# Reporte de clasificación
print("\nClassification Report:\n", classification_report(test_y, y_pred))

# Matriz de confusión
print("\nConfusion Matrix:\n", confusion_matrix(test_y, y_pred))

Accuracy: 0.8718181818181818
F1-score: [0.87488909 0.86859273]

Classification Report:
               precision    recall  f1-score   support

    negative       0.88      0.86      0.87      1622
    positive       0.87      0.88      0.87      1678

    accuracy                           0.87      3300
   macro avg       0.87      0.87      0.87      3300
weighted avg       0.87      0.87      0.87      3300


Confusion Matrix:
 [[1398  224]
 [ 199 1479]]

El modelo muestra un desempeño sólido:

Accuracy ≈ 87% indica que clasifica correctamente la gran mayoría de reseñas.

F1 ≈ 0.87 en ambas clases refleja equilibrio entre precisión y recall, sin favorecer desproporcionadamente a positivos o negativos.

El reporte de clasificación confirma que tanto la clase negativa como la positiva tienen métricas muy similares, lo que sugiere un modelo balanceado.

La matriz de confusión (1398 aciertos negativos, 1479 aciertos positivos) evidencia que los errores están distribuidos de forma moderada (224 falsos positivos y 199 falsos negativos), sin sesgo fuerte hacia una clase.